target = "specification/data-format/message-footer.md#signature-length"

# Signature Length
#
# The length of the signature.
# The length of the signature length field MUST be 2 bytes.
# The signature length value MUST be a UInt16.

[[spec]]
level = "MUST"
quote = '''
The length of the signature length field MUST be 2 bytes.
'''

[[spec]]
level = "MUST"
quote = '''
The signature length value MUST be a UInt16.
'''

