target = "specification/data-format/message-header.md#type"

# Type
#
# The type of the message format.
# The length of the serialized type field MUST be 1 byte.

[[spec]]
level = "MUST"
quote = '''
The length of the serialized type field MUST be 1 byte.
'''

