target = "specification/data-format/message-footer.md#overview"

# Overview
#
# The footer is a component of the [message](message.md).  
# When an [algorithm suite](../framework/algorithm-suites.md) includes a [signature algorithm](../framework/algorithm-suites.md#signature-algorithm),
# the [message](message.md) MUST contain a footer.

[[spec]]
level = "MUST"
quote = '''
When an [algorithm suite](../framework/algorithm-suites.md) includes a [signature algorithm](../framework/algorithm-suites.md#signature-algorithm),
the [message](message.md) MUST contain a footer.
'''

