target = "specification/data-format/message-body.md#encrypted-content-1"

# Encrypted Content
#
# The encrypted data for each frame, as returned by the [encryption algorithm](../framework/algorithm-suites.md#encryption-algorithm).  
# The length of the encrypted content of a Regular Frame MUST be equal to the Frame Length.
# The encrypted content MUST be interpreted as bytes.

[[spec]]
level = "MUST"
quote = '''
The length of the encrypted content of a Regular Frame MUST be equal to the Frame Length.
'''

[[spec]]
level = "MUST"
quote = '''
The encrypted content MUST be interpreted as bytes.
'''

