target = "specification/data-format/message-body.md#encrypted-content-length-1"

# Encrypted Content Length
#
# The length of the encrypted content.
# The length of the serialized encrypted content length field MUST be 4 bytes.
# The encrypted content length MUST be interpreted as a UInt32.

[[spec]]
level = "MUST"
quote = '''
The length of the serialized encrypted content length field MUST be 4 bytes.
'''

[[spec]]
level = "MUST"
quote = '''
The encrypted content length MUST be interpreted as a UInt32.
'''

