target = "specification/data-format/message-body.md#final-frame-encrypted-content-length"

# Final Frame Encrypted Content Length
#
# The length of the encrypted content.
# The length of the serialized encrypted content length field MUST be 4 bytes.
# The encrypted content length MUST be a UInt32.

[[spec]]
level = "MUST"
quote = '''
The length of the serialized encrypted content length field MUST be 4 bytes.
'''

[[spec]]
level = "MUST"
quote = '''
The encrypted content length MUST be a UInt32.
'''

