target = "specification/data-format/message-body.md#iv"

# IV
#
# The initialization vector to use with the encryption algorithm.
# The IV MUST be a unique IV within the message.
# The length of the serialized IV MUST be [IV Length](message-header.md#iv-length) bytes.
# The IV MUST be interpreted as bytes.

[[spec]]
level = "MUST"
quote = '''
The IV MUST be a unique IV within the message.
'''

[[spec]]
level = "MUST"
quote = '''
The length of the serialized IV MUST be [IV Length](message-header.md#iv-length) bytes.
'''

[[spec]]
level = "MUST"
quote = '''
The IV MUST be interpreted as bytes.
'''

