target = "specification/data-format/message-body.md#non-framed-data"

# Non-Framed Data
#
# Non-framed data is a sequence of encrypted bytes along with the [initialization vector (IV)](#iv)
# and body [authentication tag](#authentication-tag).
# 
# The following table is a non-normative representation of the normative requirements in this secion.
# The bytes are appended in the order shown.
# 
# | Field                                                 | Length (bytes)                           | Interpreted as |
# | ----------------------------------------------------- | ---------------------------------------- | -------------- |
# | [IV](#iv)                                             | [IV Length](message-header.md#iv-length) | Bytes          |
# | [Encrypted Content Length](#encrypted-content-length) | 8                                        | Uint64         |
# | [Encrypted Content](#encrypted-content)               | Variable                                 | Bytes          |
# | [Authentication Tag](#authentication-tag)             | Variable                                 | Bytes          |
# 
# Non-framed data MUST consist of, in order,
# IV,
# Encrypted Content Length,
# Encrypted Content,
# and Authentication Tag.

[[spec]]
level = "MUST"
quote = '''
Non-framed data MUST consist of, in order,
IV,
Encrypted Content Length,
Encrypted Content,
and Authentication Tag.
'''

