target = "specification/data-format/message-body.md#nonframed-data"

# nonframed Data
#
# nonframed data is a sequence of encrypted bytes along with the [initialization vector (IV)](#nonframed-data-iv)
# and body [authentication tag](#nonframed-data-authentication-tag).
# 
# The following table is a non-normative representation of the normative requirements in this section.
# The bytes are appended in the order shown.
# 
# | Field                                                                 | Length (bytes)                           | Interpreted as |
# | --------------------------------------------------------------------- | ---------------------------------------- | -------------- |
# | [IV](#nonframed-data-iv)                                             | [IV Length](message-header.md#iv-length) | Bytes          |
# | [Encrypted Content Length](#nonframed-data-encrypted-content-length) | 8                                        | UInt64         |
# | [Encrypted Content](#nonframed-data-encrypted-content)               | Variable                                 | Bytes          |
# | [Authentication Tag](#nonframed-data-authentication-tag)             | Variable                                 | Bytes          |
# 
# nonframed data MUST consist of, in order,
# IV,
# Encrypted Content Length,
# Encrypted Content,
# and Authentication Tag.

[[spec]]
level = "MUST"
quote = '''
nonframed data MUST consist of, in order,
IV,
Encrypted Content Length,
Encrypted Content,
and Authentication Tag.
'''

