target = "specification/data-format/message-body.md#regular-frame-authentication-tag"

# Regular Frame Authentication Tag
#
# The authentication value for the frame.  
# The authentication tag length MUST be equal to the authentication tag length of the algorithm suite
# specified by the [Algorithm Suite ID](message-header.md#algorithm-suite-id) field.
# The authentication tag MUST be interpreted as bytes.

[[spec]]
level = "MUST"
quote = '''
The authentication tag length MUST be equal to the authentication tag length of the algorithm suite
specified by the [Algorithm Suite ID](message-header.md#algorithm-suite-id) field.
'''

[[spec]]
level = "MUST"
quote = '''
The authentication tag MUST be interpreted as bytes.
'''

