use crate::client_supplier::*;
#[cfg(feature = "ddb")]
use crate::cmc::CacheType;
use crate::error::*;
pub use crate::key_agreement::{KmsEcdhStaticConfigurations, RawEcdhStaticConfigurations};
use crate::keyring::*;
#[cfg(feature = "ddb")]
use crate::keystore::KeyStoreRef;
use crate::types::*;
use async_trait::async_trait;
use aws_mpl_primitives::EcdhCurveSpec;

#[async_trait]
pub trait BranchKeyIdSupplier: Send + Sync + std::fmt::Debug {
    ///Given the Encryption Context associated with this encryption or decryption, returns the branch key that should be responsible for unwrapping or wrapping the data key.")
    async fn get_branch_key_id(
        &self,
        input: &GetBranchKeyIdInput,
    ) -> Result<GetBranchKeyIdOutput, Error>;
}

pub type BranchKeyIdSupplierRef = std::sync::Arc<dyn BranchKeyIdSupplier>;

#[derive(Debug, Clone, Default)]
#[non_exhaustive]
///Inputs for determining the Branch Key which should be used to wrap or unwrap the data key for this encryption or decryption")
pub struct GetBranchKeyIdInput {
    ///The Encryption Context used with this encryption or decryption.")
    pub encryption_context: EncryptionContext,
}

#[derive(Debug, Clone, Default)]
#[non_exhaustive]
///Outputs for the Branch Key responsible for wrapping or unwrapping the data key in this encryption or decryption.")
pub struct GetBranchKeyIdOutput {
    ///The identifier of the Branch Key that should be responsible for wrapping or unwrapping the data key in this encryption or decryption.")
    pub branch_key_id: String,
}

// Grant Tokens are base64 encoded strings
// https://docs.aws.amazon.com/kms/latest/developerguide/grants.html#grant_token
pub type GrantTokenList = Vec<String>;

#[derive(Debug, Clone, Default)]
#[non_exhaustive]
/// A filter which defines what AWS partition and AWS accounts a KMS Key may be in for a Keyring to be allowed to attempt to decrypt it.
pub struct DiscoveryFilter {
    ///A list of allowed AWS account IDs.
    pub account_ids: Vec<AccountId>,

    ///The AWS partition which is allowed.
    pub partition: String,
}

// Keyring Constructors

// KMS - Strict
///Creates an AWS KMS Keyring, which wraps and unwraps data keys using single symmetric AWS KMS Key.")
pub fn create_aws_kms_keyring(_input: &CreateAwsKmsKeyringInput) -> Result<KeyringRef, Error> {
    not_implemented("create_aws_kms_keyring")
}

#[derive(Debug, Clone, Default)]
#[non_exhaustive]
///Inputs for for creating a AWS KMS Keyring.")
pub struct CreateAwsKmsKeyringInput {
    ///The identifier for the symmetric AWS KMS Key responsible for wrapping and unwrapping data keys. This should not be a AWS KMS Multi-Region Key.")
    pub kms_key_id: KmsKeyId,

    ///The KMS Client this Keyring will use to call KMS.")
    pub kms_client: Option<aws_sdk_kms::Client>,

    ///A list of grant tokens to be used when calling KMS.")
    pub grant_tokens: GrantTokenList,
}
impl CreateAwsKmsKeyringInput {
    pub fn new(kms_key_id: impl Into<KmsKeyId>, kms_client: aws_sdk_kms::Client) -> Self {
        Self {
            kms_key_id: kms_key_id.into(),
            kms_client: Some(kms_client),
            ..Default::default()
        }
    }
    pub fn go(self) -> Result<KeyringRef, Error> {
        create_aws_kms_keyring(&self)
    }
}

///Creates an AWS KMS Multi-Keyring, which wraps and unwraps data keys using one or more symmetric AWS KMS Keys.")
pub fn create_aws_kms_multi_keyring(
    _input: CreateAwsKmsMultiKeyringInput,
) -> Result<KeyringRef, Error> {
    not_implemented("create_aws_kms_multi_keyring")
}

#[derive(Debug, Clone, Default)]
#[non_exhaustive]
///Inputs for for creating a AWS KMS Multi-Keyring.")
pub struct CreateAwsKmsMultiKeyringInput {
    ///A identifier for a symmetric AWS KMS Key responsible for wrapping and unwrapping data keys. KMS.GenerateDataKey may be called with this key if the data key has not already been generated by another Keyring. This should not be a AWS KMS Multi-Region Key.")
    pub generator: KmsKeyId,

    ///A list of identifiers for the symmetric AWS KMS Keys (other than the generator) responsible for wrapping and unwrapping data keys. This list should not contain AWS KMS Multi-Region Keys.")
    pub kms_key_ids: Vec<KmsKeyId>,

    ///The Client Supplier which will be used to get KMS Clients for use with this Keyring. The Client Supplier will create a client for each region specified in the generator and kmsKeyIds ARNs. If not specified on input, the Default Client Supplier is used.")
    pub client_supplier: Option<ClientSupplierRef>,

    ///A list of grant tokens to be used when calling KMS.")
    pub grant_tokens: GrantTokenList,
}

// KMS - Discovery
///Creates an AWS KMS Discovery Keyring, which supports unwrapping data keys wrapped by a symmetric AWS KMS Key for a single region.")
pub fn create_aws_kms_discovery_keyring(
    _input: &CreateAwsKmsDiscoveryKeyringInput,
) -> Result<KeyringRef, Error> {
    not_implemented("create_aws_kms_discovery_keyring")
}

#[derive(Debug, Clone, Default)]
#[non_exhaustive]
///Inputs for for creating a AWS KMS Discovery Keyring.")
pub struct CreateAwsKmsDiscoveryKeyringInput {
    ///The KMS Client this Keyring will use to call KMS.")
    pub kms_client: Option<aws_sdk_kms::Client>,

    ///A filter which restricts which KMS Keys this Keyring may attempt to decrypt with by AWS partition and account.")
    pub discovery_filter: DiscoveryFilter,

    ///A list of grant tokens to be used when calling KMS.")
    pub grant_tokens: GrantTokenList,
}

///Creates an AWS KMS Discovery Multi-Keyring, which supports unwrapping data keys wrapped by a symmetric AWS KMS Key, for multiple regions.")
pub fn create_aws_kms_discovery_multi_keyring(
    _input: CreateAwsKmsDiscoveryMultiKeyringInput,
) -> Result<KeyringRef, Error> {
    not_implemented("create_aws_kms_discovery_multi_keyring")
}

#[derive(Debug, Clone, Default)]
#[non_exhaustive]
///Inputs for for creating an AWS KMS Discovery Multi-Keyring.")
pub struct CreateAwsKmsDiscoveryMultiKeyringInput {
    ///The list of regions this Keyring will creates KMS clients for.")
    pub regions: Vec<Region>,

    ///A filter which restricts which KMS Keys this Keyring may attempt to decrypt with by AWS partition and account.")
    pub discovery_filter: DiscoveryFilter,

    ///The Client Supplier which will be used to get KMS Clients for use with this Keyring. If not specified on input, a Default Client Supplier is created which creates a KMS Client for each region in the 'regions' input.")
    pub client_supplier: Option<ClientSupplierRef>,

    ///A list of grant tokens to be used when calling KMS.")
    pub grant_tokens: GrantTokenList,
}

// KMS - MRK Aware, Strict
///Creates an AWS KMS MRK Keyring, which wraps and unwraps data keys using single symmetric AWS KMS Key or AWS KMS Multi-Region Key.")
pub fn create_aws_kms_mrk_keyring(
    _input: &CreateAwsKmsMrkKeyringInput,
) -> Result<KeyringRef, Error> {
    not_implemented("create_aws_kms_mrk_keyring")
}

#[derive(Debug, Clone, Default)]
#[non_exhaustive]
///Inputs for for creating an AWS KMS MRK Keyring.")
pub struct CreateAwsKmsMrkKeyringInput {
    ///The identifier for the symmetric AWS KMS Key or AWS KMS Multi-Region Key responsible for wrapping and unwrapping data keys.")
    pub kms_key_id: KmsKeyId,

    ///The KMS Client this Keyring will use to call KMS.")
    pub kms_client: Option<aws_sdk_kms::Client>,

    ///A list of grant tokens to be used when calling KMS.")
    pub grant_tokens: GrantTokenList,
}

impl CreateAwsKmsMrkKeyringInput {
    pub fn new(kms_key_id: impl Into<KmsKeyId>, kms_client: aws_sdk_kms::Client) -> Self {
        Self {
            kms_key_id: kms_key_id.into(),
            kms_client: Some(kms_client),
            ..Default::default()
        }
    }
    pub fn go(self) -> Result<KeyringRef, Error> {
        create_aws_kms_mrk_keyring(&self)
    }
}

///Creates an AWS KMS MRK Multi-Keyring, which wraps and unwraps data keys using one or more symmetric AWS KMS Keys or AWS KMS Multi-Region Keys.")
pub fn create_aws_kms_mrk_multi_keyring(
    _input: CreateAwsKmsMrkMultiKeyringInput,
) -> Result<KeyringRef, Error> {
    not_implemented("create_aws_kms_mrk_keyring")
}

#[derive(Debug, Clone, Default)]
#[non_exhaustive]
///Inputs for for creating a AWS KMS MRK Multi-Keyring.")
pub struct CreateAwsKmsMrkMultiKeyringInput {
    ///A symmetric AWS KMS Key or AWS KMS Multi-Region Key responsible for wrapping and unwrapping data keys. KMS.GenerateDataKey may be called with this key if the data key has not already been generated by another Keyring.")
    pub generator: KmsKeyId,

    ///A list of identifiers for the symmetric AWS KMS Keys and/or AWS KMS Multi-Region Keys (other than the generator) responsible for wrapping and unwrapping data keys.")
    pub kms_key_ids: Vec<KmsKeyId>,

    ///The Client Supplier which will be used to get KMS Clients for use with this Keyring. The Client Supplier will create a client for each region specified in the generator and kmsKeyIds ARNs. If not specified on input, the Default Client Supplier is used.")
    pub client_supplier: Option<ClientSupplierRef>,

    ///A list of grant tokens to be used when calling KMS.")
    pub grant_tokens: GrantTokenList,
}

// KMS - MRK Aware, Discovery

///Creates an AWS KMS MRK Discovery Keyring, which supports unwrapping data keys wrapped by a symmetric AWS KMS Key or AWS KMS Multi-Region Key in a particular region.")
pub fn create_aws_kms_mrk_discovery_keyring(
    _input: &CreateAwsKmsMrkDiscoveryKeyringInput,
) -> Result<KeyringRef, Error> {
    not_implemented("create_aws_kms_mrk_discovery_keyring")
}

#[derive(Debug, Clone, Default)]
#[non_exhaustive]
///Inputs for creating a AWS KMS MRK Discovery Keyring.")
pub struct CreateAwsKmsMrkDiscoveryKeyringInput {
    ///The KMS Client this Keyring will use to call KMS.")
    pub kms_client: Option<aws_sdk_kms::Client>,

    ///A filter which restricts which KMS Keys this Keyring may attempt to decrypt with by AWS partition and account.")
    pub discovery_filter: DiscoveryFilter,

    ///A list of grant tokens to be used when calling KMS.")
    pub grant_tokens: GrantTokenList,

    ///The region the input 'kmsClient' is in.")
    pub region: Region,
}

impl CreateAwsKmsMrkDiscoveryKeyringInput {
    #[must_use]
    pub fn new(kms_client: aws_sdk_kms::Client, region: Region) -> Self {
        Self {
            kms_client: Some(kms_client),
            region,
            ..Default::default()
        }
    }
    pub fn go(self) -> Result<KeyringRef, Error> {
        create_aws_kms_mrk_discovery_keyring(&self)
    }
}

///Creates an AWS KMS MRK Discovery Multi-Keyring that supports unwrapping data keys wrapped by a symmetric AWS KMS Key or AWS KMS Multi-Region Key, for a single region.")
pub fn create_aws_kms_mrk_discovery_multi_keyring(
    _input: CreateAwsKmsMrkDiscoveryMultiKeyringInput,
) -> Result<KeyringRef, Error> {
    not_implemented("create_aws_kms_mrk_discovery_multi_keyring")
}

#[derive(Debug, Clone, Default)]
#[non_exhaustive]
///Inputs for for creating a AWS KMS MRK Discovery Multi-Keyring.")
pub struct CreateAwsKmsMrkDiscoveryMultiKeyringInput {
    ///The list of regions this Keyring will creates KMS clients for.")
    pub regions: Vec<Region>,

    ///A filter which restricts which KMS Keys this Keyring may attempt to decrypt with by AWS partition and account.")
    pub discovery_filter: DiscoveryFilter,

    ///The Client Supplier which will be used to get KMS Clients for use with this Keyring. If not specified on input, a Default Client Supplier is created which creates a KMS Client for each region in the 'regions' input.")
    pub client_supplier: Option<ClientSupplierRef>,

    ///A list of grant tokens to be used when calling KMS.")
    pub grant_tokens: GrantTokenList,
}

impl DiscoveryFilter {
    pub fn new(partition: impl Into<String>, account_ids: Vec<AccountId>) -> Self {
        Self {
            account_ids,
            partition: partition.into(),
        }
    }
}

// KMS - Hierarchical Keyring
///Creates a Hierarchical Keyring, which supports wrapping and unwrapping data keys using Branch Keys persisted in `DynamoDB` and protected by a symmetric AWS KMS Key or AWS KMS Multi-Region Key.")
#[cfg(feature = "ddb")]
#[cfg_attr(docsrs, doc(cfg(feature = "ddb")))]
pub fn create_aws_kms_hierarchical_keyring(
    _input: CreateAwsKmsHierarchicalKeyringInput,
) -> Result<KeyringRef, Error> {
    not_implemented("create_aws_kms_hierarchical_keyring")
}

#[derive(Debug, Clone, Default)]
#[non_exhaustive]
///Inputs for creating a Hierarchical Keyring.")
#[cfg(feature = "ddb")]
#[cfg_attr(docsrs, doc(cfg(feature = "ddb")))]
pub struct CreateAwsKmsHierarchicalKeyringInput {
    // branchKeyId XOR BranchKeyIdSupplier required
    ///The identifier for the single Branch Key responsible for wrapping and unwrapping the data key. Either a Branch Key ID or Branch Key Supplier must be specified.")
    pub branch_key_id: String,
    ///A Branch Key Supplier which determines what Branch Key to use to wrap and unwrap the data key. Either a Branch Key ID or Branch Key Supplier must be specified.")
    pub branch_key_id_supplier: Option<BranchKeyIdSupplierRef>,

    ///The Key Store which contains the Branch Key(s) responsible for wrapping and unwrapping data keys.")
    pub key_store: Option<KeyStoreRef>,

    ///How many seconds the Branch Key material is allowed to be reused within the local cache before it is re-retrieved from Amazon `DynamoDB` and re-authenticated with AWS KMS.")
    pub ttl: std::time::Duration,

    /// Sets the type of cache for this Hierarchical Keyring. By providing an already initialized 'Shared' cache, users can determine the scope of the cache. That is, if the cache is shared across other Cryptographic Material Providers, for instance other Hierarchical Keyrings or Caching Cryptographic Materials Managers (Caching CMMs). If any other type of cache in the `CacheType` union is provided, the Hierarchical Keyring will initialize a cache of that type, to be used with only this Hierarchical Keyring. If not set, a `DefaultCache` is initialized to be used with only this Hierarchical Keyring with entryCapacity = 1000.
    pub cache: CacheType,

    ///Partition ID to distinguish Cryptographic Material Providers (i.e: Keyrings) writing to a cache. If the Partition ID is the same for two Hierarchical Keyrings (or another Material Provider), they can share the same cache entries in the cache.
    pub partition_id: String,
}

///Creates an AWS KMS RSA Keyring, which wraps and unwraps data keys using a single asymmetric AWS KMS Key for RSA.")
pub fn create_aws_kms_rsa_keyring(
    _input: &CreateAwsKmsRsaKeyringInput,
) -> Result<KeyringRef, Error> {
    not_implemented("create_aws_kms_rsa_keyring")
}

#[derive(Debug, Clone)] // TODO Default
#[non_exhaustive]
///Inputs for creating a AWS KMS RSA Keyring.")
pub struct CreateAwsKmsRsaKeyringInput {
    //= aws-encryption-sdk-specification/framework/aws-kms/aws-kms-rsa-keyring.md#initialization
    //= type=implication
    //# - MAY provide a PEM encoded Public Key
    ///The public RSA Key responsible for wrapping data keys, as a UTF8 encoded, PEM encoded X.509 `SubjectPublicKeyInfo` struct. This should be the public key as exported from KMS. If not specified, this Keyring cannot be used on encrypt.")
    pub public_key: Secret,
    //= aws-encryption-sdk-specification/framework/aws-kms/aws-kms-rsa-keyring.md#initialization
    //= type=implication
    //# - MUST provide an AWS KMS key identifier
    ///The ARN for the asymmetric AWS KMS Key for RSA responsible for wrapping and unwrapping data keys.")
    pub kms_key_id: KmsKeyId,
    //= aws-encryption-sdk-specification/framework/aws-kms/aws-kms-rsa-keyring.md#initialization
    //= type=implication
    //# - MUST provide an [AWS KMS Encryption Algorithm](#supported-padding-schemes)
    ///The RSA algorithm used to wrap and unwrap data keys.")
    pub encryption_algorithm: aws_sdk_kms::types::EncryptionAlgorithmSpec, // No default
    //= aws-encryption-sdk-specification/framework/aws-kms/aws-kms-rsa-keyring.md#initialization
    //= type=implication
    //# - MAY provide an AWS KMS SDK client
    ///The KMS Client this Keyring will use to call KMS.")
    pub kms_client: Option<aws_sdk_kms::Client>,
    //= aws-encryption-sdk-specification/framework/aws-kms/aws-kms-rsa-keyring.md#initialization
    //= type=implication
    //# - MAY provide a list of Grant Tokens
    ///A list of grant tokens to be used when calling KMS.")
    pub grant_tokens: GrantTokenList,
}

impl Default for CreateAwsKmsRsaKeyringInput {
    fn default() -> Self {
        Self {
            public_key: Secret::default(),
            kms_key_id: KmsKeyId::default(),
            encryption_algorithm: aws_sdk_kms::types::EncryptionAlgorithmSpec::RsaesOaepSha256,
            kms_client: None,
            grant_tokens: vec![],
        }
    }
}
impl CreateAwsKmsRsaKeyringInput {
    pub fn new(
        public_key: impl Into<Vec<u8>>,
        kms_key_id: impl Into<KmsKeyId>,
        encryption_algorithm: aws_sdk_kms::types::EncryptionAlgorithmSpec,
        kms_client: aws_sdk_kms::Client,
    ) -> Self {
        Self {
            public_key: Secret::new(public_key.into()),
            kms_key_id: kms_key_id.into(),
            encryption_algorithm,
            kms_client: Some(kms_client),
            grant_tokens: vec![],
        }
    }

    pub fn go(&self) -> Result<KeyringRef, Error> {
        create_aws_kms_rsa_keyring(self)
    }
}

///Creates an AWS KMS ECDH Keyring, which wraps and unwraps data keys by deriving a shared data key from the established shared secret between parties through the ECDH protocol.")
pub fn create_aws_kms_ecdh_keyring(
    _input: CreateAwsKmsEcdhKeyringInput,
) -> Result<KeyringRef, Error> {
    not_implemented("create_aws_kms_ecdh_keyring")
}

#[derive(Debug, Clone, Default)]
#[non_exhaustive]
///Inputs for creating an AWS KMS ECDH Keyring.")
pub struct CreateAwsKmsEcdhKeyringInput {
    ///The Key Agreement Scheme configuration that is responsible for how the shared secret is calculated.")
    pub key_agreement_scheme: KmsEcdhStaticConfigurations,

    ///The named curve that corresponds to the curve on which the sender's private and recipient's public key lie.")
    pub curve_spec: EcdhCurveSpec,

    ///The KMS Client this Keyring will use to call KMS.")
    pub kms_client: Option<aws_sdk_kms::Client>,

    ///A list of grant tokens to be used when calling KMS.")
    pub grant_tokens: GrantTokenList,
}
