target = "specification/data-format/message-body.md#final-frame-sequence-number"

# Final Frame Sequence Number
#
# The Frame sequence number for the final frame.
# The Final Frame Sequence number MUST be equal to the total number of frames in the Framed Data.
# The length of the Final Frame Sequence number field MUST be the same as the
# [Regular Frame Sequence Number](#regular-frame-sequence-number).
# The Final Frame Sequence Number MUST be interpreted as the same type as the
# [Regular Frame Sequence Number](#regular-frame-sequence-number).

[[spec]]
level = "MUST"
quote = '''
The Final Frame Sequence number MUST be equal to the total number of frames in the Framed Data.
'''

[[spec]]
level = "MUST"
quote = '''
The length of the Final Frame Sequence number field MUST be the same as the
[Regular Frame Sequence Number](#regular-frame-sequence-number).
'''

[[spec]]
level = "MUST"
quote = '''
The Final Frame Sequence Number MUST be interpreted as the same type as the
[Regular Frame Sequence Number](#regular-frame-sequence-number).
'''

