<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>EsdkTestServer</RootNamespace>
    <AssemblyName>EsdkTestServer</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- tests/ is its own project. -->
    <Compile Remove="tests/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Formats.Cbor" Version="8.0.0" />
    <ProjectReference Include="../../AwsEncryptionSDK/runtimes/net/ESDK.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="EsdkTestServer.Tests" />
  </ItemGroup>

</Project>
