target = "specification/client-apis/encrypt.md#encryption-context"

# Encryption Context
#
# See [encryption context](../framework/structures.md#encryption-context).
# 
# The prefix `aws-crypto-` is reserved for internal use by the AWS Encryption SDK;
# see the [the Default CMM spec](default-cmm.md) for one such use.
# If the input encryption context contains any entries with a key beginning with `aws-crypto-`,
# the encryption operation MUST fail.

[[spec]]
level = "MUST"
quote = '''
If the input encryption context contains any entries with a key beginning with `aws-crypto-`,
the encryption operation MUST fail.
'''

