target = "specification/client-apis/encrypt.md#output"

# Output
#
# - Encrypt operation output MUST include an [encrypted message](#encrypted-message) value.
# - Encrypt operation output MUST include an [encryption context](#encryption-context) value.
# - Encrypt operation output MUST include an [algorithm suite](#algorithm-suite) value.
# - Encrypt operation output SHOULD include a [Parsed Header](#parsed-header) value.

[[spec]]
level = "MUST"
quote = '''
- Encrypt operation output MUST include an [encrypted message](#encrypted-message) value.
'''

[[spec]]
level = "MUST"
quote = '''
- Encrypt operation output MUST include an [encryption context](#encryption-context) value.
'''

[[spec]]
level = "MUST"
quote = '''
- Encrypt operation output MUST include an [algorithm suite](#algorithm-suite) value.
'''

[[spec]]
level = "SHOULD"
quote = '''
- Encrypt operation output SHOULD include a [Parsed Header](#parsed-header) value.
'''

