target = "specification/client-apis/encrypt.md#v1-authentication-tag"

# V1 Authentication Tag
#
# With the authentication tag calculated,
# if the message format version associated with the [algorithm suite](../framework/algorithm-suites.md#supported-algorithm-suites) is 1.0
# this operation MUST serialize the [message header authentication](../data-format/message-header.md#header-authentication-version-1-0) with the following specifics:
# 
# - MUST serialize the [IV](../data-format/message-header.md#iv).
#   The value MUST be the IV used in the calculation above,
#   padded to the [IV length](../data-format/message-header.md#iv-length) with 0.
# - MUST serialize the [Authentication Tag](../data-format/message-header.md#authentication-tag).
#   The value MUST be the authentication tag calculated above.

[[spec]]
level = "MUST"
quote = '''
With the authentication tag calculated,
if the message format version associated with the [algorithm suite](../framework/algorithm-suites.md#supported-algorithm-suites) is 1.0
this operation MUST serialize the [message header authentication](../data-format/message-header.md#header-authentication-version-1-0) with the following specifics:
'''

[[spec]]
level = "MUST"
quote = '''
- MUST serialize the [IV](../data-format/message-header.md#iv).
'''

[[spec]]
level = "MUST"
quote = '''
The value MUST be the IV used in the calculation above,
padded to the [IV length](../data-format/message-header.md#iv-length) with 0.
'''

[[spec]]
level = "MUST"
quote = '''
- MUST serialize the [Authentication Tag](../data-format/message-header.md#authentication-tag).
'''

[[spec]]
level = "MUST"
quote = '''
The value MUST be the authentication tag calculated above.
'''

