// Code generated by smithy-go-codegen DO NOT EDIT.

package awscryptographyencryptionsdksmithygeneratedtypes

import (
	"fmt"
)

type AwsEncryptionSdkException struct {
	AwsEncryptionSdkBaseException
	Message           string
	ErrorCodeOverride *string
}

func (e AwsEncryptionSdkException) Error() string {
	return fmt.Sprintf("%s: %s", e.ErrorCodeOverride, e.Message)
}
