target = "spec/client-apis/decrypt.md#encryption-context"

# Encryption Context
#
# The [encryption context](../framework/structures.md#encryption-context) that is used as
# additional authenticated data during the decryption of the input [encrypted message](#encrypted-message).
# 
# This output MAY be satisfied by outputting a [parsed header](#parsed-header) containing this value.

[[spec]]
level = "MAY"
quote = '''
This output MAY be satisfied by outputting a [parsed header](#parsed-header) containing this value.
'''

