// This file is manually written, but is separated to demonstrate that
// some boilerplate could be generated by Smithy-Dafny. 
include "../../Model/AwsCryptographyEncryptionSdkTestRoundtripTypes.dfy"
include "../../../Core/Index.dfy"

abstract module AbstractTestCrossLanguageRoundTripInput refines TestVectorGeneration.PartitioningScheme
{
  import AwsCryptographyEncryptionSdkTestRoundtripTypes
  type Domain = AwsCryptographyEncryptionSdkTestRoundtripTypes.TestCrossLanguageRoundTripInput
}

abstract module AbstractTestCrossLanguageRoundTrip refines TestVectorGeneration.OperationModel
{
  import AwsCryptographyEncryptionSdkTestRoundtripTypes
  import Wrappers

  type Domain = AwsCryptographyEncryptionSdkTestRoundtripTypes.TestCrossLanguageRoundTripInput
  type Range = AwsCryptographyEncryptionSdkTestRoundtripTypes.TestCrossLanguageRoundTripOutput

  const operationName := "TestCrossLanguageRoundTrip"
}

abstract module AbstractESDKTestRoundTrip refines TestVectorGeneration.ServiceModel
{
  const serviceName := "ESDKTestRoundTrip"
  const serviceNamespace := "aws.cryptography.encryptionSdk.test.roundtrip"
}