target = "spec/data-format/message-body.md#final-frame"

# Final Frame
#
# Framed data MUST contain exactly one final frame.
# The final frame MUST be the last frame.
# 
# The length of the plaintext to be encrypted in the Final Frame MUST be
# greater than or equal to 0 and less than or equal to the [Frame Length](message-header.md#frame-length).
# 
# - When the length of the Plaintext is not an exact multiple of the Frame Length,
#   any remaining data is encrypted into the Final Frame.
# - When the length of the Plaintext is an exact multiple of the Frame Length
#   (including if it is equal to the frame length),
#   the Final Frame encrypted content length SHOULD be equal to the frame length but MAY be 0.
# - When the length of the Plaintext is less than the Frame Length,
#   the body MUST contain exactly one frame and that frame MUST be a Final Frame.
# 
# For example, in the case that the length of the Plaintext is equal to the Frame Length, there are two acceptable cases:
# 
# - The body contains exactly one frame, the final frame,
#   with a content length equal to the plaintext length.
# - The body contains two frames.
#   The first frame is a regular frame,
#   and the second frame is the final frame with a content length of 0.
# 
# The following table is a non-normative representation of the normative requirements in this section.
# 
# | Field                                                             | Length (bytes)                                                                                               | Interpreted as |
# | ----------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------ | -------------- |
# | [Sequence Number End](#sequence-number-end)                       | 4                                                                                                            | Bytes          |
# | [Sequence Number](#final-frame-sequence-number)                   | 4                                                                                                            | UInt32         |
# | [IV](#final-frame-iv)                                             | [IV Length](message-header.md#iv-length)                                                                     | Bytes          |
# | [Encrypted Content Length](#final-frame-encrypted-content-length) | 4                                                                                                            | UInt32         |
# | [Encrypted Content](#final-frame-encrypted-content)               | Variable                                                                                                     | Bytes          |
# | [Authentication Tag](#final-frame-authentication-tag)             | Algorithm suite ID's [Authentication Tag Length](../framework/algorithm-suites.md#authentication-tag-length) | Bytes          |
# 
# A final frame MUST consist of, in order,
# Sequence Number End,
# Sequence Number,
# IV,
# Encrypted Content Length,
# Encrypted Content,
# and Authentication Tag.
# 
# A final frame MUST only differ from a regular frame by the addition of the
# Sequence Number End
# and Encrypted Content Length.

[[spec]]
level = "MUST"
quote = '''
Framed data MUST contain exactly one final frame.
'''

[[spec]]
level = "MUST"
quote = '''
The final frame MUST be the last frame.
'''

[[spec]]
level = "MUST"
quote = '''
The length of the plaintext to be encrypted in the Final Frame MUST be
greater than or equal to 0 and less than or equal to the [Frame Length](message-header.md#frame-length).
'''

[[spec]]
level = "SHOULD"
quote = '''
- When the length of the Plaintext is an exact multiple of the Frame Length
(including if it is equal to the frame length),
the Final Frame encrypted content length SHOULD be equal to the frame length but MAY be 0.
'''

[[spec]]
level = "MUST"
quote = '''
- When the length of the Plaintext is less than the Frame Length,
the body MUST contain exactly one frame and that frame MUST be a Final Frame.
'''

[[spec]]
level = "MUST"
quote = '''
A final frame MUST consist of, in order,
Sequence Number End,
Sequence Number,
IV,
Encrypted Content Length,
Encrypted Content,
and Authentication Tag.
'''

[[spec]]
level = "MUST"
quote = '''
A final frame MUST only differ from a regular frame by the addition of the
Sequence Number End
and Encrypted Content Length.
'''

