target = "spec/data-format/message-body.md#framed-data"

# Framed Data
#
# Framed data is a sequence of bytes divided into equal-length parts called frames.  
# Each frame is encrypted separately with a unique [IV](#regular-frame-iv) and body [authentication tag](#regular-frame-authentication-tag).
# There are two kinds of frames:
# 
# - [Regular Frame](#regular-frame)
# - [Final Frame](#final-frame)
# 
# Note:
# 
# - The total bytes allowed in a single frame MUST be less than or equal to `2^32 - 1`.
# - The number of frames in a single message MUST be less than or equal to `2^32 - 1`.

[[spec]]
level = "MUST"
quote = '''
- The total bytes allowed in a single frame MUST be less than or equal to `2^32 - 1`.
'''

[[spec]]
level = "MUST"
quote = '''
- The number of frames in a single message MUST be less than or equal to `2^32 - 1`.
'''

