target = "spec/client-apis/encrypt.md#algorithm-suite"

# Algorithm Suite
#
# The [algorithm suite](../framework/algorithm-suites.md) that MUST be used for encryption.
# This algorithm suite MUST be [supported for the ESDK](../framework/algorithm-suites.md#supported-algorithm-suites-enum).

[[spec]]
level = "MUST"
quote = '''
The [algorithm suite](../framework/algorithm-suites.md) that MUST be used for encryption.
'''

[[spec]]
level = "MUST"
quote = '''
This algorithm suite MUST be [supported for the ESDK](../framework/algorithm-suites.md#supported-algorithm-suites-enum).
'''

