target = "spec/shim/shim.md#concurrency"

# Concurrency
#
# If a core library resource or operation supports concurrent use from multiple threads,
# the shim library SHOULD support it as well.

[[spec]]
level = "SHOULD"
quote = '''
If a core library resource or operation supports concurrent use from multiple threads,
the shim library SHOULD support it as well.
'''

