target = "spec/shim/shim.md#streaming"

# Streaming
#
# If a core library resource or operation supports [streamed](../client-apis/streaming.md) input/outputs,
# the shim library SHOULD support it as well.

[[spec]]
level = "SHOULD"
quote = '''
If a core library resource or operation supports [streamed](../client-apis/streaming.md) input/outputs,
the shim library SHOULD support it as well.
'''

