target = "specification/data-format/message-header.md#key-value-pairs"

# Key Value Pairs
#
# The encoding of the key-value pairs of the [encryption context](../framework/structures.md#encryption-context),
# serialized according to it's [specification for serialization](../framework/structures.md#serialization).
# 
# When the [encryption context](../framework/structures.md#encryption-context) is empty,
# this field MUST NOT be included in the [AAD](#aad).

[[spec]]
level = "MUST"
quote = '''
When the [encryption context](../framework/structures.md#encryption-context) is empty,
this field MUST NOT be included in the [AAD](#aad).
'''

