target = "specification/data-format/message-header.md#version"

# Version
#
# The version of the message format.
# The version (hex) of this field MUST be a value that exists in the following table:

[[spec]]
level = "MUST"
quote = '''
The version (hex) of this field MUST be a value that exists in the following table:
'''

