target = "specification/client-apis/encrypt.md#authentication-tag"

# Authentication Tag
#
# After serializing the message header body,
# this operation MUST calculate an [authentication tag](../data-format/message-header.md#authentication-tag)
# over the message header body.
# The value of this MUST be the output of the [authenticated encryption algorithm](../framework/algorithm-suites.md#encryption-algorithm)
# specified by the [algorithm suite](../framework/algorithm-suites.md), with the following inputs:
# 
# - The AAD MUST be the concatenation of the serialized [message header body](../data-format/message-header.md#header-body)
#   and the serialization of encryption context to only authenticate.
#   The encryption context to only authenticate MUST be the [encryption context](../framework/structures.md#encryption-context)
#   in the [encryption materials](../framework/structures.md#encryption-materials)
#   filtered to only contain key value pairs listed in
#   the [encryption material's](../framework/structures.md#encryption-materials)
#   [required encryption context keys](../framework/structures.md#required-encryption-context-keys)
#   serialized according to the [encryption context serialization specification](../framework/structures.md#serialization).
# - The IV MUST have a value of 0.
# - The cipherkey MUST be the derived data key
# - The plaintext MUST be an empty byte array
# 
# With the authentication tag calculated,
# if the message format version associated with the [algorithm suite](../framework/algorithm-suites.md#supported-algorithm-suites) is 2.0,
# this operation MUST serialize the [message header authentication](../data-format/message-header.md#header-authentication-version-2-0) with the following specifics:
# 
# - [Authentication Tag](../data-format/message-header.md#authentication-tag): MUST have the value
#   of the authentication tag calculated above.
# 
# With the authentication tag calculated,
# if the message format version associated with the [algorithm suite](../framework/algorithm-suites.md#supported-algorithm-suites) is 1.0
# this operation MUST serialize the [message header authentication](../data-format/message-header.md#header-authentication-version-1-0) with the following specifics:
# 
# - [IV](../data-format/message-header.md#iv): MUST have the value of the IV used in the calculation above,
#   padded to the [IV length](../data-format/message-header.md#iv-length) with 0.
# - [Authentication Tag](../data-format/message-header.md#authentication-tag): MUST have the value
#   of the authentication tag calculated above.
# 
# The serialized bytes MUST NOT be released until the entire message header has been serialized.
# If this operation is streaming the encrypted message and
# the entire message header has been serialized,
# the serialized message header MUST be released.
# 
# The encrypted message output by the Encrypt operation MUST have a message header equal
# to the message header calculated in this step.
# If the message headers are not equal, the Encrypt operation MUST fail.
# 
# If the algorithm suite contains a signature algorithm and
# this operation is [streaming](streaming.md) the encrypted message output to the caller,
# this operation MUST input the serialized header to the signature algorithm as soon as it is serialized,
# such that the serialized header isn't required to remain in memory to [construct the signature](#construct-the-signature).

[[spec]]
level = "MUST"
quote = '''
After serializing the message header body,
this operation MUST calculate an [authentication tag](../data-format/message-header.md#authentication-tag)
over the message header body.
'''

[[spec]]
level = "MUST"
quote = '''
The value of this MUST be the output of the [authenticated encryption algorithm](../framework/algorithm-suites.md#encryption-algorithm)
specified by the [algorithm suite](../framework/algorithm-suites.md), with the following inputs:
'''

[[spec]]
level = "MUST"
quote = '''
- The AAD MUST be the concatenation of the serialized [message header body](../data-format/message-header.md#header-body)
and the serialization of encryption context to only authenticate.
'''

[[spec]]
level = "MUST"
quote = '''
The encryption context to only authenticate MUST be the [encryption context](../framework/structures.md#encryption-context)
in the [encryption materials](../framework/structures.md#encryption-materials)
filtered to only contain key value pairs listed in
the [encryption material's](../framework/structures.md#encryption-materials)
[required encryption context keys](../framework/structures.md#required-encryption-context-keys)
serialized according to the [encryption context serialization specification](../framework/structures.md#serialization).
'''

[[spec]]
level = "MUST"
quote = '''
- The IV MUST have a value of 0.
'''

[[spec]]
level = "MUST"
quote = '''
- The cipherkey MUST be the derived data key
'''

[[spec]]
level = "MUST"
quote = '''
- The plaintext MUST be an empty byte array
'''

[[spec]]
level = "MUST"
quote = '''
With the authentication tag calculated,
if the message format version associated with the [algorithm suite](../framework/algorithm-suites.md#supported-algorithm-suites) is 2.0,
this operation MUST serialize the [message header authentication](../data-format/message-header.md#header-authentication-version-2-0) with the following specifics:
'''

[[spec]]
level = "MUST"
quote = '''
- [Authentication Tag](../data-format/message-header.md#authentication-tag): MUST have the value
of the authentication tag calculated above.
'''

[[spec]]
level = "MUST"
quote = '''
With the authentication tag calculated,
if the message format version associated with the [algorithm suite](../framework/algorithm-suites.md#supported-algorithm-suites) is 1.0
this operation MUST serialize the [message header authentication](../data-format/message-header.md#header-authentication-version-1-0) with the following specifics:
'''

[[spec]]
level = "MUST"
quote = '''
- [IV](../data-format/message-header.md#iv): MUST have the value of the IV used in the calculation above,
padded to the [IV length](../data-format/message-header.md#iv-length) with 0.
'''

[[spec]]
level = "MUST"
quote = '''
The serialized bytes MUST NOT be released until the entire message header has been serialized.
'''

[[spec]]
level = "MUST"
quote = '''
If this operation is streaming the encrypted message and
the entire message header has been serialized,
the serialized message header MUST be released.
'''

[[spec]]
level = "MUST"
quote = '''
The encrypted message output by the Encrypt operation MUST have a message header equal
to the message header calculated in this step.
'''

[[spec]]
level = "MUST"
quote = '''
If the message headers are not equal, the Encrypt operation MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
If the algorithm suite contains a signature algorithm and
this operation is [streaming](streaming.md) the encrypted message output to the caller,
this operation MUST input the serialized header to the signature algorithm as soon as it is serialized,
such that the serialized header isn't required to remain in memory to [construct the signature](#construct-the-signature).
'''

