target = "specification/client-apis/encrypt.md#un-framed-message-body-encryption"

# Un-Framed Message Body Encryption
#
# Implementations of the AWS Encryption SDK MUST NOT encrypt using the Non-Framed content type.

[[spec]]
level = "MUST"
quote = '''
Implementations of the AWS Encryption SDK MUST NOT encrypt using the Non-Framed content type.
'''

