target = "spec/shim/esdk-shim.md#cache-configuration"

# Cache configuration
#
# - The shim MUST translate a no-cache selection.
# - The shim MUST translate a multi-threaded cache selection.
# - The shim MUST return an error when the target cache type is not a supported
#   value.

[[spec]]
level = "MUST"
quote = '''
- The shim MUST translate a no-cache selection.
'''

[[spec]]
level = "MUST"
quote = '''
- The shim MUST translate a multi-threaded cache selection.
'''

[[spec]]
level = "MUST"
quote = '''
- The shim MUST return an error when the target cache type is not a supported
value.
'''

