target = "spec/shim/esdk-shim.md#create-kms-client"

# Create KMS client
#
# - The shim MUST provide an operation that creates a KMS service client backed by
#   the core ESDK.
# - Creating a KMS client MUST apply the target-supplied client configuration, as
#   defined in [Service client configuration](#service-client-configuration).

[[spec]]
level = "MUST"
quote = '''
- The shim MUST provide an operation that creates a KMS service client backed by
the core ESDK.
'''

[[spec]]
level = "MUST"
quote = '''
- Creating a KMS client MUST apply the target-supplied client configuration, as
defined in [Service client configuration](#service-client-configuration).
'''

