target = "spec/shim/esdk-shim.md#decrypt-inputs"

# Decrypt inputs
#
# - `decrypt` MUST pass the target-supplied ciphertext to the core ESDK unmodified.
# - `decrypt` MUST provide the target-supplied encryption context to the core ESDK,
#   converted as defined in [Encryption context](#encryption-context).
# - `decrypt` MUST provide the target-supplied commitment policy to the core ESDK,
#   converted as defined in [Commitment policy](#commitment-policy).
# - `decrypt` MUST provide the target-supplied maximum-encrypted-data-keys value to
#   the core ESDK, converted as defined in
#   [Maximum encrypted data keys](#maximum-encrypted-data-keys).

[[spec]]
level = "MUST"
quote = '''
- `decrypt` MUST pass the target-supplied ciphertext to the core ESDK unmodified.
'''

[[spec]]
level = "MUST"
quote = '''
- `decrypt` MUST provide the target-supplied encryption context to the core ESDK,
converted as defined in [Encryption context](#encryption-context).
'''

[[spec]]
level = "MUST"
quote = '''
- `decrypt` MUST provide the target-supplied commitment policy to the core ESDK,
converted as defined in [Commitment policy](#commitment-policy).
'''

[[spec]]
level = "MUST"
quote = '''
- `decrypt` MUST provide the target-supplied maximum-encrypted-data-keys value to
the core ESDK, converted as defined in
[Maximum encrypted data keys](#maximum-encrypted-data-keys).
'''

