target = "spec/shim/esdk-shim.md#encrypt-inputs"

# Encrypt inputs
#
# - `encrypt` MUST pass the target-supplied plaintext to the core ESDK unmodified.
# - `encrypt` MUST provide the target-supplied encryption context to the core ESDK,
#   converted as defined in [Encryption context](#encryption-context).
# - `encrypt` MUST provide the target-supplied algorithm suite to the core ESDK,
#   converted as defined in [Algorithm suite identifier](#algorithm-suite-identifier).
# - `encrypt` MUST provide the target-supplied commitment policy to the core ESDK,
#   converted as defined in [Commitment policy](#commitment-policy).
# - `encrypt` MUST provide the target-supplied frame length to the core ESDK,
#   converted as defined in [Frame length](#frame-length).
# - `encrypt` MUST provide the target-supplied maximum-encrypted-data-keys value to
#   the core ESDK, converted as defined in
#   [Maximum encrypted data keys](#maximum-encrypted-data-keys).

[[spec]]
level = "MUST"
quote = '''
- `encrypt` MUST pass the target-supplied plaintext to the core ESDK unmodified.
'''

[[spec]]
level = "MUST"
quote = '''
- `encrypt` MUST provide the target-supplied encryption context to the core ESDK,
converted as defined in [Encryption context](#encryption-context).
'''

[[spec]]
level = "MUST"
quote = '''
- `encrypt` MUST provide the target-supplied algorithm suite to the core ESDK,
converted as defined in [Algorithm suite identifier](#algorithm-suite-identifier).
'''

[[spec]]
level = "MUST"
quote = '''
- `encrypt` MUST provide the target-supplied commitment policy to the core ESDK,
converted as defined in [Commitment policy](#commitment-policy).
'''

[[spec]]
level = "MUST"
quote = '''
- `encrypt` MUST provide the target-supplied frame length to the core ESDK,
converted as defined in [Frame length](#frame-length).
'''

[[spec]]
level = "MUST"
quote = '''
- `encrypt` MUST provide the target-supplied maximum-encrypted-data-keys value to
the core ESDK, converted as defined in
[Maximum encrypted data keys](#maximum-encrypted-data-keys).
'''

