target = "spec/shim/esdk-shim.md#encrypt-outputs"

# Encrypt outputs
#
# - `encrypt` MUST return the core ESDK's ciphertext unmodified.
# - `encrypt` MUST return the used algorithm suite, converted as defined in
#   [Algorithm suite identifier](#algorithm-suite-identifier).
# - `encrypt` MUST return the result encryption context, converted as defined in
#   [Encryption context](#encryption-context).

[[spec]]
level = "MUST"
quote = '''
- `encrypt` MUST return the core ESDK's ciphertext unmodified.
'''

[[spec]]
level = "MUST"
quote = '''
- `encrypt` MUST return the used algorithm suite, converted as defined in
[Algorithm suite identifier](#algorithm-suite-identifier).
'''

[[spec]]
level = "MUST"
quote = '''
- `encrypt` MUST return the result encryption context, converted as defined in
[Encryption context](#encryption-context).
'''

