target = "specification/client-apis/decrypt.md#nonframed-message-body-decryption"

# Nonframed Message Body Decryption
#
# Implementations of the ESDK cannot encrypt messages with nonframed message bodies but still support decrypting messages with nonframed message bodies.
# 
# Nonframed data deserialization MUST conform to the [Nonframed Data](../data-format/message-body.md#nonframed-data) specification.
# 
# If a message has the [nonframed](../data-format/message-body.md#nonframed-data) content type,
# the Decrypt operation MUST deserialize the message body according to the
# [nonframed data specification](../data-format/message-body.md#nonframed-data)
# and decrypt it using the [authenticated encryption algorithm](../framework/algorithm-suites.md#encryption-algorithm)
# specified by the [algorithm suite](../framework/algorithm-suites.md), with the following inputs:
# 
# - The IV MUST be the [IV](../data-format/message-body.md#nonframed-data-iv) deserialized from the message body.
# - The ciphertext MUST be the [Encrypted Content](../data-format/message-body.md#nonframed-data-encrypted-content) deserialized from the message body.
# - The cipherkey MUST be the derived data key.
# - The tag MUST be the [Authentication Tag](../data-format/message-body.md#nonframed-data-authentication-tag) deserialized from the message body.
# - The AAD MUST be the serialized [message body AAD](../data-format/message-body-aad.md),
#   constructed with:
#   - The [Body AAD Content](../data-format/message-body-aad.md#body-aad-content) MUST use the value for
#     [nonframed data](../data-format/message-body-aad.md#body-aad-content).
#   - The [sequence number](../data-format/message-body-aad.md#sequence-number) MUST be `1`.
#   - The [content length](../data-format/message-body-aad.md#content-length) MUST equal the length of the plaintext.
# 
# If this decryption fails, this operation MUST immediately halt and fail.

[[spec]]
level = "MUST"
quote = '''
Nonframed data deserialization MUST conform to the [Nonframed Data](../data-format/message-body.md#nonframed-data) specification.
'''

[[spec]]
level = "MUST"
quote = '''
If a message has the [nonframed](../data-format/message-body.md#nonframed-data) content type,
the Decrypt operation MUST deserialize the message body according to the
[nonframed data specification](../data-format/message-body.md#nonframed-data)
and decrypt it using the [authenticated encryption algorithm](../framework/algorithm-suites.md#encryption-algorithm)
specified by the [algorithm suite](../framework/algorithm-suites.md), with the following inputs:
'''

[[spec]]
level = "MUST"
quote = '''
- The IV MUST be the [IV](../data-format/message-body.md#nonframed-data-iv) deserialized from the message body.
'''

[[spec]]
level = "MUST"
quote = '''
- The ciphertext MUST be the [Encrypted Content](../data-format/message-body.md#nonframed-data-encrypted-content) deserialized from the message body.
'''

[[spec]]
level = "MUST"
quote = '''
- The cipherkey MUST be the derived data key.
'''

[[spec]]
level = "MUST"
quote = '''
- The tag MUST be the [Authentication Tag](../data-format/message-body.md#nonframed-data-authentication-tag) deserialized from the message body.
'''

[[spec]]
level = "MUST"
quote = '''
- The AAD MUST be the serialized [message body AAD](../data-format/message-body-aad.md),
constructed with:
'''

[[spec]]
level = "MUST"
quote = '''
- The [Body AAD Content](../data-format/message-body-aad.md#body-aad-content) MUST use the value for
[nonframed data](../data-format/message-body-aad.md#body-aad-content).
'''

[[spec]]
level = "MUST"
quote = '''
- The [sequence number](../data-format/message-body-aad.md#sequence-number) MUST be `1`.
'''

[[spec]]
level = "MUST"
quote = '''
- The [content length](../data-format/message-body-aad.md#content-length) MUST equal the length of the plaintext.
'''

[[spec]]
level = "MUST"
quote = '''
If this decryption fails, this operation MUST immediately halt and fail.
'''

