target = "specification/client-apis/decrypt.md#parse-the-header"

# Parse the header
#
# Given encrypted message bytes, this operation MUST process those bytes sequentially,
# deserializing those bytes according to the [message format](../data-format/message.md).
# 
# This operation MUST attempt to deserialize all consumable encrypted message bytes until it has
# successfully deserialized a valid [message header](../data-format/message-header.md).
# 
# The header deserialization order MUST follow the [Header Body Version 1.0](../data-format/message-header.md#header-body-version-10)
# or [Header Body Version 2.0](../data-format/message-header.md#header-body-version-20) specification,
# depending on the [Version](../data-format/message-header.md#version) field.
# 
# The [Version](../data-format/message-header.md#version) field MUST be deserialized first.
# The value MUST be a [supported version](../data-format/message-header.md#supported-versions).

[[spec]]
level = "MUST"
quote = '''
Given encrypted message bytes, this operation MUST process those bytes sequentially,
deserializing those bytes according to the [message format](../data-format/message.md).
'''

[[spec]]
level = "MUST"
quote = '''
This operation MUST attempt to deserialize all consumable encrypted message bytes until it has
successfully deserialized a valid [message header](../data-format/message-header.md).
'''

[[spec]]
level = "MUST"
quote = '''
The header deserialization order MUST follow the [Header Body Version 1.0](../data-format/message-header.md#header-body-version-10)
or [Header Body Version 2.0](../data-format/message-header.md#header-body-version-20) specification,
depending on the [Version](../data-format/message-header.md#version) field.
'''

[[spec]]
level = "MUST"
quote = '''
The [Version](../data-format/message-header.md#version) field MUST be deserialized first.
'''

[[spec]]
level = "MUST"
quote = '''
The value MUST be a [supported version](../data-format/message-header.md#supported-versions).
'''

