from aws_encryption_sdk_dafny.smithygenerated.aws_cryptography_encryptionsdk.models import (
    EncryptInput,
    DecryptInput,
)
from aws_cryptographic_material_providers.mpl.models import CreateRawAesKeyringInput
from aws_cryptographic_material_providers.mpl.client import AwsCryptographicMaterialProviders
from aws_cryptographic_material_providers.mpl.config import MaterialProvidersConfig