clippy:
	cargo clippy --tests --examples
	cargo clippy --tests --examples --features fips

test:
	cargo test
	cargo test --no-default-features --features fips

examples:
	echo no primitives examples yet
