// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0

package main

import (
	primitivestypes "github.com/aws/aws-cryptographic-material-providers-library/primitives/awscryptographyprimitivessmithygeneratedtypes"
	"github.com/aws/aws-encryption-sdk/examples/clientsupplier"
	"github.com/aws/aws-encryption-sdk/examples/cryptographicmaterialsmanager/requiredencryptioncontext"
	"github.com/aws/aws-encryption-sdk/examples/cryptographicmaterialsmanager/restrictalgorithmsuite"
	"github.com/aws/aws-encryption-sdk/examples/keyring/awskmsdiscoverykeyring"
	"github.com/aws/aws-encryption-sdk/examples/keyring/awskmsdiscoverymultikeyring"
	"github.com/aws/aws-encryption-sdk/examples/keyring/awskmshierarchicalkeyring"
	"github.com/aws/aws-encryption-sdk/examples/keyring/awskmskeyring"
	"github.com/aws/aws-encryption-sdk/examples/keyring/awskmsmrkdiscoverykeyring"
	"github.com/aws/aws-encryption-sdk/examples/keyring/awskmsmrkdiscoverymultikeyring"
	"github.com/aws/aws-encryption-sdk/examples/keyring/awskmsmrkkeyring"
	"github.com/aws/aws-encryption-sdk/examples/keyring/awskmsmrkmultikeyring"
	"github.com/aws/aws-encryption-sdk/examples/keyring/awskmsmultikeyring"
	"github.com/aws/aws-encryption-sdk/examples/keyring/awskmsrsakeyring"
	"github.com/aws/aws-encryption-sdk/examples/keyring/ecdh"
	"github.com/aws/aws-encryption-sdk/examples/keyring/multikeyring"
	"github.com/aws/aws-encryption-sdk/examples/keyring/rawaeskeyring"
	"github.com/aws/aws-encryption-sdk/examples/keyring/rawrsakeyring"
	"github.com/aws/aws-encryption-sdk/examples/misc"
	"github.com/aws/aws-encryption-sdk/examples/utils"
)

func main() {
	const stringToEncrypt = "Text To encrypt"
	clientsupplier.ClientSupplierExample(
		stringToEncrypt,
		utils.GetDefaultRegionMrkKeyArn(),
		utils.GetDefaultKMSKeyAccountID(),
		[]string{"eu-west-1"})
	misc.CommitmentPolicyExample(
		stringToEncrypt,
		utils.GetDefaultKMSKeyId(),
		utils.GetDefaultKmsKeyRegion())
	misc.SetEncryptionAlgorithmSuiteExample(stringToEncrypt)
	var maxEncryptedDataKeys int64 = 3
	misc.LimitEncryptedDataKeyExample(
		stringToEncrypt,
		utils.GetDefaultKMSKeyId(),
		utils.GetDefaultKmsKeyRegion(),
		maxEncryptedDataKeys)
	requiredencryptioncontext.RequiredEncryptionContextExample(
		stringToEncrypt,
		utils.GetDefaultKMSKeyId(),
		utils.GetDefaultKmsKeyRegion())
	restrictalgorithmsuite.SigningOnlyExample(
		stringToEncrypt,
		utils.GetDefaultKMSKeyId(),
		utils.GetDefaultKmsKeyRegion())
	// keyrings
	ecdh.PublicKeyRawEcdhDiscoveryKeyringExample(
		stringToEncrypt,
		primitivestypes.ECDHCurveSpecEccNistP256,
		utils.GetEccPublicKeyFileNameRecipient(),
		utils.GetEccPrivateKeyFileNameRecipient())
	ecdh.EphemeralRawECDHKeyringExample(
		stringToEncrypt,
		primitivestypes.ECDHCurveSpecEccNistP256,
		utils.GetEccPublicKeyFileNameRecipient())
	ecdh.RawECDHKeyringExample(
		stringToEncrypt,
		primitivestypes.ECDHCurveSpecEccNistP256,
		utils.GetEccPublicKeyFileNameRecipient(),
		utils.GetEccPrivateKeyFileNameSender())
	ecdh.AwsKmsEcdhKeyringExample(
		stringToEncrypt,
		primitivestypes.ECDHCurveSpecEccNistP256,
		utils.GetKmsEcdhKeyIdP256RecipientKeyId(),
		utils.GetKmsEcdhKeyIdP256SenderKeyId(),
		utils.GetKmsEccPublicKeyFileNameSender(),
		utils.GetKmsEccPublicKeyFileNameRecipient())
	ecdh.AwsKmsEcdhDiscoveryKeyringExample(
		stringToEncrypt,
		primitivestypes.ECDHCurveSpecEccNistP256,
		utils.GetKmsEcdhKeyIdP256RecipientKeyId(),
		utils.GetKmsEcdhKeyIdP256SenderKeyId(),
		utils.GetKmsEccPublicKeyFileNameSender(),
		utils.GetKmsEccPublicKeyFileNameRecipient())
	awskmskeyring.AwsKmsKeyringExample(
		stringToEncrypt,
		utils.GetDefaultKMSKeyId(),
		utils.GetDefaultKMSKeyAccountID())
	awskmsrsakeyring.AwsKmsRsaExample(
		stringToEncrypt,
		utils.GetTestKmsRsaKeyID(),
		utils.GetKmsRSAPublicKey())
	awskmsmultikeyring.AwsKmsMultiKeyringExample(
		stringToEncrypt,
		utils.GetDefaultKMSKeyId(),
		utils.GetAlternateRegionKMSKeyId(),
		utils.GetAlternateRegionKMSKeyRegion())
	awskmsdiscoverykeyring.AwsKmsDiscoveryKeyringExample(
		stringToEncrypt,
		utils.GetDefaultKMSKeyId(),
		utils.GetDefaultKMSKeyAccountID())
	awskmsdiscoverymultikeyring.AwsKmsDiscoveryMultiKeyringExample(
		stringToEncrypt,
		utils.GetDefaultKMSKeyId(),
		utils.GetDefaultKMSKeyAccountID(),
		utils.GetRegions())
	rawrsakeyring.RawRsaExample(stringToEncrypt)
	awskmsmrkkeyring.AwsKmsMrkKeyringExample(
		stringToEncrypt,
		utils.GetDefaultRegionMrkKeyArn(),
		utils.GetAlternateRegionMrkKeyArn(),
		utils.GetDefaultMRKKeyRegion(),
		utils.GetAlternateRegionMrkKeyRegion())
	awskmsmrkmultikeyring.AwsKmsMrkMultiKeyringExample(
		stringToEncrypt,
		utils.GetDefaultRegionMrkKeyArn(),
		utils.GetAlternateRegionMrkKeyArn(),
		utils.GetDefaultKMSKeyId(),
		utils.GetAlternateRegionMrkKeyRegion())
	awskmsmrkdiscoverykeyring.AwsKmsMrkDiscoveryKeyringExample(
		stringToEncrypt,
		utils.GetDefaultRegionMrkKeyArn(),
		utils.GetDefaultMRKKeyRegion(),
		utils.GetAlternateRegionMrkKeyRegion(),
		utils.GetDefaultKMSKeyAccountID())
	awskmsmrkdiscoverymultikeyring.AwsKmsMrkDiscoveryMultiKeyringExample(
		stringToEncrypt,
		utils.GetDefaultRegionMrkKeyArn(),
		utils.GetDefaultMRKKeyRegion(),
		utils.GetDefaultKMSKeyAccountID(),
		utils.GetRegionsOfMRKKeys(),
	)
	awskmshierarchicalkeyring.AwsKmsHKeyExample(
		stringToEncrypt,
		utils.GetKeyStoreKMSKeyRegion(),
		utils.GetKeyStoreRegion(),
		utils.GetKeyStoreKMSKeyID(),
		utils.GetKeyStoreName(),
		utils.GetLogicalKeyStoreName(),
	)
	awskmshierarchicalkeyring.CreateAndVersionBranchKeyId(
		utils.GetKeyStoreKMSKeyRegion(),
		utils.GetKeyStoreRegion(),
		utils.GetKeyStoreKMSKeyID(),
		utils.GetKeyStoreName(),
		utils.GetLogicalKeyStoreName(),
	)
	awskmshierarchicalkeyring.SharedCacheExample(
		stringToEncrypt,
		utils.GetKeyStoreKMSKeyRegion(),
		utils.GetKeyStoreRegion(),
		utils.GetKeyStoreKMSKeyID(),
		utils.GetKeyStoreName(),
		utils.GetLogicalKeyStoreName(),
	)
	rawaeskeyring.RawAesExample(stringToEncrypt)
	multikeyring.MultiKeyringExample(
		stringToEncrypt,
		utils.GetDefaultKMSKeyId(),
		utils.GetDefaultKmsKeyRegion(),
	)
}
