clippy:
	cd prim && make clippy
	cd mpl && make clippy
	cd esdk && make clippy
	cd aws-esdk-cxx && make clippy

test:
	cd prim && make test
	cd mpl && make test
	cd esdk && make test
	cd aws-esdk-cxx && make test

examples:
	cd mpl && make examples
	cd esdk && make examples
