// This file is manually written, but is separated to demonstrate that
// some boilerplate could be generated by Smithy-Dafny. 
include "../../../Core/Index.dfy"
include "../../../../../mpl/AwsCryptographicMaterialProviders/dafny/AwsCryptographicMaterialProviders/Model/AwsCryptographyMaterialProvidersTypes.dfy"

abstract module AbstractCreateRawAesKeyringInput refines TestVectorGeneration.PartitioningScheme
{
    import AwsCryptographyMaterialProvidersTypes
    type ValueType = AwsCryptographyMaterialProvidersTypes.CreateRawAesKeyringInput
}

abstract module AbstractCreateRawAesKeyringSmokeTest refines TestVectorGeneration.OperationModel
{
    import AwsCryptographyMaterialProvidersTypes
    import Wrappers

    type Domain = AwsCryptographyMaterialProvidersTypes.CreateRawAesKeyringInput
    type Range = string

    const operationName := "CreateRawAesKeyringSmokeTest"
}

abstract module AbstractCreateRawAesKeyringTestService refines TestVectorGeneration.ServiceModel
{
    import AwsCryptographyMaterialProvidersTypes
    import Wrappers

    const serviceName := "CreateRawAesKeyringTestService"
}