target = "specification/data-format/message-body-aad.md#message-id"

# Message ID
#
# An identifier for the [message](message.md) this message body AAD is associated with.
# This MUST be the [message ID](message-header.md#message-id) stored in the header of the message.
# The length of the Message ID field MUST be equal to the length of the [Message ID](message-header.md#message-id) defined by the message header version.

[[spec]]
level = "MUST"
quote = '''
This MUST be the [message ID](message-header.md#message-id) stored in the header of the message.
'''

[[spec]]
level = "MUST"
quote = '''
The length of the Message ID field MUST be equal to the length of the [Message ID](message-header.md#message-id) defined by the message header version.
'''

