// Code generated by smithy-go-codegen DO NOT EDIT.

package awscryptographyencryptionsdksmithygeneratedtypes

type NetV4_0_0_RetryPolicy string

const (
	NetV4_0_0_RetryPolicyForbidRetry NetV4_0_0_RetryPolicy = "FORBID_RETRY"
	NetV4_0_0_RetryPolicyAllowRetry  NetV4_0_0_RetryPolicy = "ALLOW_RETRY"
)

func (NetV4_0_0_RetryPolicy) Values() []NetV4_0_0_RetryPolicy {
	return []NetV4_0_0_RetryPolicy{
		"FORBID_RETRY",
		"ALLOW_RETRY",
	}
}
