target = "specification/client-apis/decrypt.md#authenticated-data"

# Authenticated Data
#
# Plaintext or associated data is considered authenticated if the associated
# authentication tag is successfully checked
# as defined by the algorithm suite indicated in the message header.
# The authentication tag may be from a [regular frame](../data-format/message-body.md#regular-frame-authentication-tag),
# [final frame](../data-format/message-body.md#final-frame-authentication-tag),
# or [non-framed data](../data-format/message-body.md#non-framed-data-authentication-tag).
# 
# This operation MUST NOT release any unauthenticated plaintext or unauthenticated associated data.

[[spec]]
level = "MUST"
quote = '''
This operation MUST NOT release any unauthenticated plaintext or unauthenticated associated data.
'''

