target = "specification/client-apis/decrypt.md#behavior"

# Behavior
#
# The Decrypt operation is divided into several distinct steps:
# 
# - Decrypt operation Step 1 MUST be [Parse the header](#parse-the-header)
# - Decrypt operation Step 2 MUST be [Get the decryption materials](#get-the-decryption-materials)
# - Decrypt operation Step 3 MUST be [Verify the header](#verify-the-header)
# - Decrypt operation Step 4 MUST be [Decrypt the message body](#decrypt-the-message-body)
# - Decrypt operation Step 5 MUST be [Verify the signature](#verify-the-signature)
#   - If the message header contains an algorithm suite including a
#     [signature algorithm](../framework/algorithm-suites.md#signature-algorithm),
#     the Decrypt operation MUST perform this step.
#   - If the message header does not contain an algorithm suite including a signature algorithm,
#     the Decrypt operation MUST NOT perform this step.
# 
# If the input encrypted message is not being [streamed](streaming.md) to this operation,
# all output MUST NOT be released until after these steps complete successfully.
# 
# If the input encrypted message is being [streamed](streaming.md) to this operation:
# 
# - Output MUST NOT be released until otherwise indicated.
# - If all bytes have been provided and this operation
#   is unable to complete the above steps with the consumable encrypted message bytes,
#   this operation MUST halt and indicate a failure to the caller.
# - If this operation successfully completes the above steps
#   but there are consumable bytes which are intended to be decrypted,
#   this operation MUST fail.
# - The ESDK MUST provide a configuration option that causes the decryption operation
#   to fail immediately after parsing the header if a signed algorithm suite is used.
#   This can be used to ensure that data not yet [verified as signed data](#security-considerations)
#   is never released early.

[[spec]]
level = "MUST"
quote = '''
- Decrypt operation Step 1 MUST be [Parse the header](#parse-the-header)
'''

[[spec]]
level = "MUST"
quote = '''
- Decrypt operation Step 2 MUST be [Get the decryption materials](#get-the-decryption-materials)
'''

[[spec]]
level = "MUST"
quote = '''
- Decrypt operation Step 3 MUST be [Verify the header](#verify-the-header)
'''

[[spec]]
level = "MUST"
quote = '''
- Decrypt operation Step 4 MUST be [Decrypt the message body](#decrypt-the-message-body)
'''

[[spec]]
level = "MUST"
quote = '''
- Decrypt operation Step 5 MUST be [Verify the signature](#verify-the-signature)
'''

[[spec]]
level = "MUST"
quote = '''
- If the message header contains an algorithm suite including a
[signature algorithm](../framework/algorithm-suites.md#signature-algorithm),
the Decrypt operation MUST perform this step.
'''

[[spec]]
level = "MUST"
quote = '''
- If the message header does not contain an algorithm suite including a signature algorithm,
the Decrypt operation MUST NOT perform this step.
'''

[[spec]]
level = "MUST"
quote = '''
If the input encrypted message is not being [streamed](streaming.md) to this operation,
all output MUST NOT be released until after these steps complete successfully.
'''

[[spec]]
level = "MUST"
quote = '''
- Output MUST NOT be released until otherwise indicated.
'''

[[spec]]
level = "MUST"
quote = '''
- If all bytes have been provided and this operation
is unable to complete the above steps with the consumable encrypted message bytes,
this operation MUST halt and indicate a failure to the caller.
'''

[[spec]]
level = "MUST"
quote = '''
- If this operation successfully completes the above steps
but there are consumable bytes which are intended to be decrypted,
this operation MUST fail.
'''

[[spec]]
level = "MUST"
quote = '''
- The ESDK MUST provide a configuration option that causes the decryption operation
to fail immediately after parsing the header if a signed algorithm suite is used.
'''

