target = "specification/client-apis/client.md#initialization"

# Initialization
#
# - On client initialization,
#   the caller MUST have the option to provide a [commitment policy](#commitment-policy).
# - On client initialization,
#   the caller MUST have the option to provide a [maximum number of encrypted data keys](#maximum-number-of-encrypted-data-keys).
# 
# If no [commitment policy](#commitment-policy) is provided the default MUST be [REQUIRE_ENCRYPT_REQUIRE_DECRYPT](../framework/algorithm-suites.md#require_encrypt_require_decrypt).
# If no [maximum number of encrypted data keys](#maximum-number-of-encrypted-data-keys) is provided
# the default MUST result in no limit on the number of encrypted data keys (aside from the limit imposed by the [message format](../format/message-header.md)).
# 
# Once a [commitment policy](#commitment-policy) has been set it SHOULD be immutable.

[[spec]]
level = "MUST"
quote = '''
- On client initialization,
the caller MUST have the option to provide a [commitment policy](#commitment-policy).
'''

[[spec]]
level = "MUST"
quote = '''
- On client initialization,
the caller MUST have the option to provide a [maximum number of encrypted data keys](#maximum-number-of-encrypted-data-keys).
'''

[[spec]]
level = "MUST"
quote = '''
If no [commitment policy](#commitment-policy) is provided the default MUST be [REQUIRE_ENCRYPT_REQUIRE_DECRYPT](../framework/algorithm-suites.md#require_encrypt_require_decrypt).
'''

[[spec]]
level = "MUST"
quote = '''
If no [maximum number of encrypted data keys](#maximum-number-of-encrypted-data-keys) is provided
the default MUST result in no limit on the number of encrypted data keys (aside from the limit imposed by the [message format](../format/message-header.md)).
'''

[[spec]]
level = "SHOULD"
quote = '''
Once a [commitment policy](#commitment-policy) has been set it SHOULD be immutable.
'''

