target = "spec/data-format/message-header.md#encrypted-data-keys"

# Encrypted Data Keys
#
# The encoding of the [encrypted data keys](../framework/structures.md#encrypted-data-key).
# 
# The following table is a non-normative representation of the normative requirements in this section.
# 
# | Field                                                     | Length, in bytes                                                     | Interpreted as                                            |
# | --------------------------------------------------------- | -------------------------------------------------------------------- | --------------------------------------------------------- |
# | [Encrypted Data Key Count](#encrypted-data-key-count)     | 2                                                                    | UInt16                                                    |
# | [Encrypted Data Key Entries](#encrypted-data-key-entries) | Variable. Determined by the count and length of each key-value pair. | [Encrypted Data Key Entries](#encrypted-data-key-entries) |
# 
# The Encrypted Data Keys MUST consist of, in order,
# Encrypted Data Key Count,
# and Encrypted Data Key Entries.

[[spec]]
level = "MUST"
quote = '''
The Encrypted Data Keys MUST consist of, in order,
Encrypted Data Key Count,
and Encrypted Data Key Entries.
'''

