target = "spec/data-format/message-header.md#key-value-pairs-length"

# Key Value Pairs Length
#
# The length of the [Key Value Pairs](#key-value-pairs) field in bytes.
# The length of the serialized key value pairs length field MUST be 2 bytes.
# The key value pairs length MUST be interpreted as a UInt16.
# 
# When the [encryption context](../framework/structures.md#encryption-context) is empty, the value of this field MUST be 0.

[[spec]]
level = "MUST"
quote = '''
The length of the serialized key value pairs length field MUST be 2 bytes.
'''

[[spec]]
level = "MUST"
quote = '''
The key value pairs length MUST be interpreted as a UInt16.
'''

[[spec]]
level = "MUST"
quote = '''
When the [encryption context](../framework/structures.md#encryption-context) is empty, the value of this field MUST be 0.
'''

