target = "spec/data-format/message-header.md#supported-types"

# Supported Types
#
# The supported types MUST be:
# 
# - `80` MUST be Customer Authenticated Encrypted Data
# 
# The following table is a non-normative representation of the supported types.
# 
# | Value (hex) | Type                                  |
# | ----------- | ------------------------------------- |
# | 80          | Customer Authenticated Encrypted Data |

[[spec]]
level = "MUST"
quote = '''
The supported types MUST be:
'''

[[spec]]
level = "MUST"
quote = '''
- `80` MUST be Customer Authenticated Encrypted Data
'''

