target = "spec/data-format/message-header.md#version"

# Version
#
# The version of the message format.
# The length of the serialized version field MUST be 1 byte.

[[spec]]
level = "MUST"
quote = '''
The length of the serialized version field MUST be 1 byte.
'''

