# This workflow performs static analysis checks.
name: static analysis

on: ["pull_request"]

jobs:
  not-grep:
    runs-on: ubuntu-latest
    steps:
      - uses: Wandalen/wretry.action@master
        with:
          action: actions/checkout@v6
          attempt_limit: 3
          attempt_delay: 2000
      - name: not-grep
        uses: mattsb42-meta/not-grep@1.0.1
