# This workflow reads the project.properties
# into the environment variables
# and then creates an output variable for `dafnyVersion`
name: Dafny Version

on:
  workflow_call:
    outputs:
      version:
        description: "The dafny version"
        value: ${{ jobs.getDafnyVersion.outputs.version }}

jobs:
  getDafnyVersion:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.read_property.outputs.dafnyVersion }}
    steps:
      - uses: Wandalen/wretry.action@master
        with:
          action: actions/checkout@v6
          attempt_limit: 3
          attempt_delay: 2000
      - name: Read version from Properties-file
        id: read_property
        uses: Wandalen/wretry.action@master
        with:
          action: christian-draeger/read-properties@1.1.1
          with: |
            path: "./project.properties"
            properties: "dafnyVersion"
          attempt_limit: 3
          attempt_delay: 2000
