# This workflow runs every weekday at 15:00 UTC (8AM PDT)
name: Daily CI

on:
  schedule:
    - cron: "00 15 * * 1-5"
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  getVersion:
    uses: ./.github/workflows/dafny_version.yaml
  getVerifyVersion:
    uses: ./.github/workflows/dafny_verify_version.yaml
  # not yet used, because we don't actually CI formatting in this project?!?
  getFormatVersion:
    uses: ./.github/workflows/dafny_format_version.yaml
  pr-ci-format:
    needs: getFormatVersion
    uses: ./.github/workflows/library_format.yml
    with:
      dafny: ${{needs.getFormatVersion.outputs.version}}
  daily-ci-codegen:
    # Don't run the cron builds on forks
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    needs: getVersion
    uses: ./.github/workflows/library_codegen.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
  daily-ci-verification:
    # Don't run the cron builds on forks
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    needs: getVerifyVersion
    uses: ./.github/workflows/library_dafny_verification.yml
    with:
      dafny: ${{needs.getVerifyVersion.outputs.version}}
  # daily-ci-java:
  #   if: github.event_name != 'schedule' || github.repository_owner == 'aws'
  #   uses: ./.github/workflows/library_java_tests.yml
  #   with:
  #     dafny: '4.2.0'
  daily-ci-net:
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    needs: getVersion
    uses: ./.github/workflows/library_net_tests.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
  daily-ci-rust:
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    needs: getVersion
    uses: ./.github/workflows/library_rust_tests.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
  daily-ci-go:
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    needs: getVersion
    uses: ./.github/workflows/library_go_tests.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}

  daily-ci-interop-tests:
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    needs: getVersion
    uses: ./.github/workflows/library_interop_tests.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}

  daily-dafny-keyring-test-vectors:
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    needs: getVersion
    uses: ./.github/workflows/library_interop_keyring_test_vectors.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}

  pr-dafny-mkp-keyring-legacy-test-vectors:
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    needs: getVersion
    uses: ./.github/workflows/library_interop_mkp_test_vectors.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}

  daily-dafny-legacy-test-vectors:
    if: github.event_name != 'schedule' || github.repository_owner == 'aws'
    needs: getVersion
    uses: ./.github/workflows/library_legacy_interop_test_vectors.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}

  notify:
    needs:
      [
        getVersion,
        getVerifyVersion,
        getFormatVersion,
        pr-ci-format,
        daily-ci-codegen,
        daily-ci-verification,
        daily-ci-net,
        daily-ci-rust,
        daily-ci-go,
        daily-ci-interop-tests,
        daily-dafny-keyring-test-vectors,
        pr-dafny-mkp-keyring-legacy-test-vectors,
        daily-dafny-legacy-test-vectors,
      ]
    if: ${{ failure() }}
    uses: aws/aws-cryptographic-material-providers-library/.github/workflows/slack-notification.yml@main
    with:
      message: "Daily CI failed on `${{ github.repository }}`. View run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CI }}
