name: ESDK Rust Tests

on:
  push:
    branches:
      - aws-crypto-rust/unreviewed

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Support longpaths on Git checkout
        run: git config --global core.longpaths true

      - uses: actions/checkout@v5

      - name: Init Submodules
        run: git submodule update --init --recursive dafny-mpl

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::370957321024:role/GitHub-CI-Public-ESDK-Dafny-Role-us-west-2
          role-session-name: EsdkRustNativeTests

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Run ESDK tests
        run: |
          cat > Cargo.toml << 'WKSP'
          [workspace]
          resolver = "3"
          members = ["prim", "mpl", "esdk"]
          WKSP
          rm -f Cargo.lock
          cargo test --release -p aws-esdk
