# This workflow runs for every pull request
name: PR CI

on:
  pull_request:

jobs:
  pr-ci-codegen:
    uses: ./.github/workflows/library_codegen.yml
    with:
      dafny: '4.9.0'
  pr-ci-verification:
    uses: ./.github/workflows/library_dafny_verification.yml
    with:
      dafny: '4.9.0'
  # pr-ci-java:
  #   uses: ./.github/workflows/library_java_tests.yml
  #   with:
  #     dafny: '4.2.0'
  pr-ci-net:
    uses: ./.github/workflows/library_net_tests.yml
    with:
      dafny: '4.9.0'
  pr-ci-rust:
    uses: ./.github/workflows/library_rust_tests.yml
    with:
      dafny: '4.9.0'
  pr-test-vectors:
    uses: ./.github/workflows/library_interop_tests.yml
    with:
      dafny: '4.9.0'
  pr-dafny-test-vectors:
    uses: ./.github/workflows/library_interop_test_vectors.yml
    with:
      dafny: '4.9.0'
  pr-dafny-legacy-test-vectors:
    uses: ./.github/workflows/library_legacy_interop_test_vectors.yml
    with:
      dafny: '4.9.0'
  pr-ci-all-required:
    if: always()
    needs:
      - pr-ci-codegen
      - pr-ci-verification
      - pr-ci-net
      - pr-ci-rust
      - pr-test-vectors
      - pr-dafny-test-vectors
      - pr-dafny-legacy-test-vectors
    runs-on: ubuntu-latest
    steps:
      - name: Verify all required jobs passed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
