# This workflow runs for every pull request
name: PR CI

on:
  pull_request:

jobs:
  getVersion:
    uses: ./.github/workflows/dafny_version.yaml
  pr-dafny-test-vectors:
    needs: getVersion
    uses: ./.github/workflows/library_interop_test_vectors.yml
    with:
      dafny: ${{needs.getVersion.outputs.version}}
